driver:
  name: docker
  use_sudo: false
  remove_images: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.15.19
# roles_path: ~/gitrepos/roles
  environments_path: test/integration/environments
#  data_bags_path: test/integration/data_bags
  client_rb:
    environment: chefdemodev

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[realdoc-repo::altirepo]
      - recipe[rediscluster]
    attributes:
