driver:
  name: docker
  use_sudo: false
  remove_images: true

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.6.0
  environments_path: test/integration/environments
  client_rb:
    environment: chefdemodev

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[rediscluster]
    attributes:
